#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Get user selection via dmenu from emoji file.
# chosen=$(cut -d ';' -f1 ~/.local/share/larbs/emoji | dmenu -i -l 30 | sed "s/ .*//")

# # Exit if none chosen.
# [ -z "$chosen" ] && exit

# # If you run this command with an argument, it will automatically insert the
# # character. Otherwise, show a message that the emoji has been copied.
# if [ -n "$1" ]; then
# 	xdotool type "$chosen"
# else
# 	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
# 	notify-send "'$chosen' copied to clipboard." &
# fi


# The famous "get a menu of emojis to copy" script.

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

chosen=$(grep -v "#" ~/bin/emoji | dmenu -i -l 25 -fn "Monospace 15" )

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "'$c' copied to clipboard." &

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip
notify-send "'$s' copied to primary." &
